// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import type * as pomme_launcher$auth from "./pomme_launcher/auth";
import type * as pomme_launcher$commands from "./pomme_launcher/commands";
import type * as pomme_launcher$installations from "./pomme_launcher/installations";
import type * as pomme_launcher$ping from "./pomme_launcher/ping";
import type * as pomme_launcher$settings from "./pomme_launcher/settings";

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAllAccounts: () => __TAURI_INVOKE<pomme_launcher$auth.AuthAccount[]>("get_all_accounts"),
	addAccount: () => typedError<pomme_launcher$auth.AuthAccount, string>(__TAURI_INVOKE("add_account")),
	removeAccount: (uuid: string) => __TAURI_INVOKE<void>("remove_account", { uuid }),
	ensureAssets: (version: string) => typedError<null, string>(__TAURI_INVOKE("ensure_assets", { version })),
	getVersions: (showSnapshots: boolean | null) => typedError<pomme_launcher$commands.GameVersion[], string>(__TAURI_INVOKE("get_versions", { showSnapshots })),
	refreshAccount: (uuid: string) => typedError<pomme_launcher$auth.AuthAccount, string>(__TAURI_INVOKE("refresh_account", { uuid })),
	getSkinUrl: (uuid: string) => typedError<string, string>(__TAURI_INVOKE("get_skin_url", { uuid })),
	getPatchNotes: (count: number | null) => typedError<pomme_launcher$commands.PatchNote[], string>(__TAURI_INVOKE("get_patch_notes", { count })),
	getPatchContent: (contentPath: string) => typedError<string, string>(__TAURI_INVOKE("get_patch_content", { contentPath })),
	launchGame: (version: string, uuid: string | null, server: string | null, debugEnabled: boolean | null, installPath: string | null) => typedError<string, string>(__TAURI_INVOKE("launch_game", { version, uuid, server, debugEnabled, installPath })),
	getClientLogs: () => typedError<string[], null>(__TAURI_INVOKE("get_client_logs")),
	loadLauncherSettings: () => __TAURI_INVOKE<pomme_launcher$settings.LauncherSettings>("load_launcher_settings"),
	setLauncherLanguage: (language: string) => typedError<null, string>(__TAURI_INVOKE("set_launcher_language", { language })),
	setKeepLauncherOpen: (keep: boolean) => typedError<null, string>(__TAURI_INVOKE("set_keep_launcher_open", { keep })),
	setLaunchWithConsole: (launch: boolean) => typedError<null, string>(__TAURI_INVOKE("set_launch_with_console", { launch })),
	pingServer: (address: string) => __TAURI_INVOKE<pomme_launcher$ping.ServerStatus>("ping_server", { address }),
	loadServers: () => __TAURI_INVOKE<pomme_launcher$ping.SavedServer[]>("load_servers"),
	saveServers: (servers: pomme_launcher$ping.SavedServer[]) => typedError<null, string>(__TAURI_INVOKE("save_servers", { servers })),
	loadInstallations: () => typedError<pomme_launcher$installations.Installation[], pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("load_installations")),
	createInstallation: (payload: pomme_launcher$installations.InstallationDraft) => typedError<pomme_launcher$installations.Installation, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("create_installation", { payload })),
	deleteInstallation: (id: string) => typedError<null, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("delete_installation", { id })),
	duplicateInstallation: (oldId: string, payload: pomme_launcher$installations.InstallationDraft) => typedError<pomme_launcher$installations.Installation, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("duplicate_installation", { oldId, payload })),
	editInstallation: (id: string, payload: pomme_launcher$installations.InstallationDraft) => typedError<pomme_launcher$installations.Installation, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("edit_installation", { id, payload })),
	getDownloadedVersions: () => __TAURI_INVOKE<string[]>("get_downloaded_versions"),
};

/* Tauri Specta runtime */
export type Result<T, E> =
  | { ok: true;  value: T }
  | { ok: false; error: E };

export const Result = {
  ok<T>(value: T): Result<T, never> {
    return { ok: true, value };
  },
  err<E>(error: E): Result<never, E> {
    return { ok: false, error };
  },
} as const;


export async function typedError<T, E>(promise: Promise<T>): Promise<Result<T, E>> {
  try {
    return Result.ok(await promise);
  } catch (e) {
    if (e instanceof Error) throw e;
    return Result.err(e as E);
  }
}

const _assertTypedErrorFollowsContract: <T, E>(result: Promise<T>) => Promise<any> = typedError;
